experiment_name: llama3_h4
text_source: llama3
max_encoder_length: 4
max_prediction_length: 4
max_epochs: 150
batch_size: 64
learning_rate: 0.001
hidden_size: 64
attention_heads: 4
dropout: 0.15
weight_decay: 1.0e-5
